INSERT INTO MOVIE (MOVIE_NAME, MOVIE_POSTER_URL,MOVIE_TAGS) VALUES ('Tiger','url for image','test1');
INSERT INTO MOVIE (MOVIE_NAME, MOVIE_POSTER_URL,MOVIE_TAGS) VALUES ('Hum','url for image','test2');

INSERT INTO THEATRE (THEATRE_NAME, THEATRE_CITY) VALUES ('Pvr','Delhi');
INSERT INTO THEATRE (THEATRE_NAME, THEATRE_CITY) VALUES ('Galaxy','Ghaziabad');
INSERT INTO THEATRE (THEATRE_NAME, THEATRE_CITY) VALUES ('DLF','Noida');

INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi1',300,1);
INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi2',200,1);
INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi1',300,2);
INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi2',200,2);
INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi1',300,3);
INSERT INTO SCREEN (SCREEN_NAME, SEATS_NUM, THEATRE_ID) VALUES ('Audi2',200,3);

INSERT INTO MOVIESHOW (SCREEN_ID ,MOVIE_ID,MOVIESHOW_DATE,MOVIESHOW_TIME,BOOKED_TICKETS) VALUES(1,1,'2021-11-04','20:30:00',1);
INSERT INTO MOVIESHOW (SCREEN_ID ,MOVIE_ID,MOVIESHOW_DATE,MOVIESHOW_TIME,BOOKED_TICKETS) VALUES(2,2,'2021-11-04','20:30:00',1);