DROP TABLE IF EXISTS MOVIE;
DROP TABLE IF EXISTS THEATRE;
DROP TABLE IF EXISTS SCREEN;
DROP TABLE IF EXISTS MOVIESHOW;
  
CREATE TABLE MOVIE (
  MOVIE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  MOVIE_NAME VARCHAR(250) NOT NULL,
  MOVIE_POSTER_URL VARCHAR(500),
  MOVIE_TAGS VARCHAR(500)
);

  
CREATE TABLE THEATRE (
  THEATRE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  THEATRE_NAME VARCHAR(250) NOT NULL,
  THEATRE_CITY VARCHAR(250) NOT NULL
);

CREATE TABLE SCREEN (
  SCREEN_ID INT AUTO_INCREMENT  PRIMARY KEY,
  SCREEN_NAME VARCHAR(250) NOT NULL,
  SEATS_NUM INT NOT NULL,
  THEATRE_ID INT NOT NULL
);

CREATE TABLE MOVIESHOW (
  MOVIESHOW_ID INT AUTO_INCREMENT  PRIMARY KEY,
  SCREEN_ID INT NOT NULL,
  MOVIE_ID INT NOT NULL,
  MOVIESHOW_DATE DATE,
  MOVIESHOW_TIME TIME,
  BOOKED_TICKETS INT NOT NULL
);
